// Code generated by "gen-const -p convert -o convert/constant.go -use64flg"; DO NOT EDIT.
package convert

const (
	maxUint8  = ^uint8(0)
	minUint8  = 0
	maxInt8   = int8(maxUint8 >> 1)
	minInt8   = -maxInt8 - 1
	maxUint16 = ^uint16(0)
	minUint16 = 0
	maxInt16  = int16(maxUint16 >> 1)
	minInt16  = -maxInt16 - 1
	maxUint32 = ^uint32(0)
	minUint32 = 0
	maxInt32  = int32(maxUint32 >> 1)
	minInt32  = -maxInt32 - 1
	maxUint64 = ^uint64(0)
	minUint64 = 0
	maxInt64  = int64(maxUint64 >> 1)
	minInt64  = -maxInt64 - 1
	maxUint   = ^uint(0)
	minUint   = 0
	maxInt    = int(maxUint >> 1)
	minInt    = -maxInt - 1
)

var is64 bool

func init() {
	is64 = maxInt64 == int64(maxInt)
}
