// Code generated by "gen-int -t int16 -o convert/int16.go"; DO NOT EDIT.
package convert

import (
	"errors"
	"strconv"
)

func ToInt16(v interface{}) (int16, error) {
	if v == nil {
		return 0, ErrNil
	}
	switch vt := v.(type) {

	case int8:
		return int16(vt), nil
	case *int8:
		if vt == nil {
			return 0, ErrNil
		}
		return int16(*vt), nil

	case int16:
		return vt, nil
	case *int16:
		if vt == nil {
			return 0, ErrNil
		}
		return *vt, nil

	case int32:
		if vt < int32(minInt16) || int32(maxInt16) < vt {
			return 0, &RangeError{"int32", "int16", vt}
		}
		return int16(vt), nil
	case *int32:
		if vt == nil {
			return 0, ErrNil
		}
		if *vt < int32(minInt16) || int32(maxInt16) < *vt {
			return 0, &RangeError{"*int32", "int16", *vt}
		}
		return int16(*vt), nil

	case int64:
		if vt < int64(minInt16) || int64(maxInt16) < vt {
			return 0, &RangeError{"int64", "int16", vt}
		}
		return int16(vt), nil
	case *int64:
		if vt == nil {
			return 0, ErrNil
		}
		if *vt < int64(minInt16) || int64(maxInt16) < *vt {
			return 0, &RangeError{"*int64", "int16", *vt}
		}
		return int16(*vt), nil

	case int:
		if vt < int(minInt16) || int(maxInt16) < vt {
			return 0, &RangeError{"int", "int16", vt}
		}
		return int16(vt), nil
	case *int:
		if vt == nil {
			return 0, ErrNil
		}
		if *vt < int(minInt16) || int(maxInt16) < *vt {
			return 0, &RangeError{"*int", "int16", *vt}
		}
		return int16(*vt), nil

	case uint8:
		return int16(vt), nil
	case *uint8:
		if vt == nil {
			return 0, ErrNil
		}
		return int16(*vt), nil

	case uint16:
		if uint16(maxInt16) < vt {
			return 0, &RangeError{"uint16", "int16", vt}
		}
		return int16(vt), nil
	case *uint16:
		if vt == nil {
			return 0, ErrNil
		}
		if uint16(maxInt16) < *vt {
			return 0, &RangeError{"*uint16", "int16", *vt}
		}
		return int16(*vt), nil

	case uint32:
		if uint32(maxInt16) < vt {
			return 0, &RangeError{"uint32", "int16", vt}
		}
		return int16(vt), nil
	case *uint32:
		if vt == nil {
			return 0, ErrNil
		}
		if uint32(maxInt16) < *vt {
			return 0, &RangeError{"*uint32", "int16", *vt}
		}
		return int16(*vt), nil

	case uint64:
		if uint64(maxInt16) < vt {
			return 0, &RangeError{"uint64", "int16", vt}
		}
		return int16(vt), nil
	case *uint64:
		if vt == nil {
			return 0, ErrNil
		}
		if uint64(maxInt16) < *vt {
			return 0, &RangeError{"*uint64", "int16", *vt}
		}
		return int16(*vt), nil

	case uint:
		if uint(maxInt16) < vt {
			return 0, &RangeError{"uint", "int16", vt}
		}
		return int16(vt), nil
	case *uint:
		if vt == nil {
			return 0, ErrNil
		}
		if uint(maxInt16) < *vt {
			return 0, &RangeError{"*uint", "int16", *vt}
		}
		return int16(*vt), nil

	case string:
		n, err := strconv.ParseInt(vt, 10, 16)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"string", "int16", vt}
			}
			return 0, err
		}
		r, err := ToInt16(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "string"
		}
		return r, err
	case *string:
		if vt == nil {
			return 0, ErrNil
		}
		n, err := strconv.ParseInt(*vt, 10, 16)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"*string", "int16", *vt}
			}
			return 0, err
		}
		r, err := ToInt16(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "*string"
		}
		return r, err

	}
	return 0, ErrNoNumConvert
}

func ToInt16P(v interface{}) (*int16, error) {
	if v == nil {
		return nil, nil
	}
	switch vt := v.(type) {

	case int8:
		casted := int16(vt)
		return &casted, nil
	case *int8:
		if vt == nil {
			return nil, nil
		}
		casted := int16(*vt)
		return &casted, nil

	case int16:
		return &vt, nil
	case *int16:
		return vt, nil

	case int32:
		if vt < int32(minInt16) || int32(maxInt16) < vt {
			return nil, &RangeError{"int32", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *int32:
		if vt == nil {
			return nil, nil
		}
		if *vt < int32(minInt16) || int32(maxInt16) < *vt {
			return nil, &RangeError{"*int32", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case int64:
		if vt < int64(minInt16) || int64(maxInt16) < vt {
			return nil, &RangeError{"int64", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *int64:
		if vt == nil {
			return nil, nil
		}
		if *vt < int64(minInt16) || int64(maxInt16) < *vt {
			return nil, &RangeError{"*int64", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case int:
		if vt < int(minInt16) || int(maxInt16) < vt {
			return nil, &RangeError{"int", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *int:
		if vt == nil {
			return nil, nil
		}
		if *vt < int(minInt16) || int(maxInt16) < *vt {
			return nil, &RangeError{"*int", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case uint8:
		casted := int16(vt)
		return &casted, nil
	case *uint8:
		if vt == nil {
			return nil, nil
		}
		casted := int16(*vt)
		return &casted, nil

	case uint16:
		if uint16(maxInt16) < vt {
			return nil, &RangeError{"uint16", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *uint16:
		if vt == nil {
			return nil, nil
		}
		if uint16(maxInt16) < *vt {
			return nil, &RangeError{"*uint16", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case uint32:
		if uint32(maxInt16) < vt {
			return nil, &RangeError{"uint32", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *uint32:
		if vt == nil {
			return nil, nil
		}
		if uint32(maxInt16) < *vt {
			return nil, &RangeError{"*uint32", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case uint64:
		if uint64(maxInt16) < vt {
			return nil, &RangeError{"uint64", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *uint64:
		if vt == nil {
			return nil, nil
		}
		if uint64(maxInt16) < *vt {
			return nil, &RangeError{"*uint64", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case uint:
		if uint(maxInt16) < vt {
			return nil, &RangeError{"uint", "*int16", vt}
		}
		casted := int16(vt)
		return &casted, nil
	case *uint:
		if vt == nil {
			return nil, nil
		}
		if uint(maxInt16) < *vt {
			return nil, &RangeError{"*uint", "*int16", *vt}
		}
		casted := int16(*vt)
		return &casted, nil

	case string:
		n, err := strconv.ParseInt(vt, 10, 16)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"string", "*int16", vt}
			}
			return nil, err
		}
		r, err := ToInt16P(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "string"
		}
		return r, err
	case *string:
		if vt == nil {
			return nil, nil
		}
		n, err := strconv.ParseInt(*vt, 10, 16)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"*string", "*int16", *vt}
			}
			return nil, err
		}
		r, err := ToInt16P(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "*string"
		}
		return r, err

	}
	return nil, ErrNoNumConvert
}
