// Code generated by "gen-int -t int32 -o convert/int32.go"; DO NOT EDIT.
package convert

import (
	"errors"
	"strconv"
)

func ToInt32(v interface{}) (int32, error) {
	if v == nil {
		return 0, ErrNil
	}
	switch vt := v.(type) {

	case int8:
		return int32(vt), nil
	case *int8:
		if vt == nil {
			return 0, ErrNil
		}
		return int32(*vt), nil

	case int16:
		return int32(vt), nil
	case *int16:
		if vt == nil {
			return 0, ErrNil
		}
		return int32(*vt), nil

	case int32:
		return vt, nil
	case *int32:
		if vt == nil {
			return 0, ErrNil
		}
		return *vt, nil

	case int64:
		if vt < int64(minInt32) || int64(maxInt32) < vt {
			return 0, &RangeError{"int64", "int32", vt}
		}
		return int32(vt), nil
	case *int64:
		if vt == nil {
			return 0, ErrNil
		}
		if *vt < int64(minInt32) || int64(maxInt32) < *vt {
			return 0, &RangeError{"*int64", "int32", *vt}
		}
		return int32(*vt), nil

	case int:
		if vt < int(minInt32) || int(maxInt32) < vt {
			return 0, &RangeError{"int", "int32", vt}
		}
		return int32(vt), nil
	case *int:
		if vt == nil {
			return 0, ErrNil
		}
		if *vt < int(minInt32) || int(maxInt32) < *vt {
			return 0, &RangeError{"*int", "int32", *vt}
		}
		return int32(*vt), nil

	case uint8:
		return int32(vt), nil
	case *uint8:
		if vt == nil {
			return 0, ErrNil
		}
		return int32(*vt), nil

	case uint16:
		return int32(vt), nil
	case *uint16:
		if vt == nil {
			return 0, ErrNil
		}
		return int32(*vt), nil

	case uint32:
		if uint32(maxInt32) < vt {
			return 0, &RangeError{"uint32", "int32", vt}
		}
		return int32(vt), nil
	case *uint32:
		if vt == nil {
			return 0, ErrNil
		}
		if uint32(maxInt32) < *vt {
			return 0, &RangeError{"*uint32", "int32", *vt}
		}
		return int32(*vt), nil

	case uint64:
		if uint64(maxInt32) < vt {
			return 0, &RangeError{"uint64", "int32", vt}
		}
		return int32(vt), nil
	case *uint64:
		if vt == nil {
			return 0, ErrNil
		}
		if uint64(maxInt32) < *vt {
			return 0, &RangeError{"*uint64", "int32", *vt}
		}
		return int32(*vt), nil

	case uint:
		if uint(maxInt32) < vt {
			return 0, &RangeError{"uint", "int32", vt}
		}
		return int32(vt), nil
	case *uint:
		if vt == nil {
			return 0, ErrNil
		}
		if uint(maxInt32) < *vt {
			return 0, &RangeError{"*uint", "int32", *vt}
		}
		return int32(*vt), nil

	case string:
		n, err := strconv.ParseInt(vt, 10, 32)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"string", "int32", vt}
			}
			return 0, err
		}
		r, err := ToInt32(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "string"
		}
		return r, err
	case *string:
		if vt == nil {
			return 0, ErrNil
		}
		n, err := strconv.ParseInt(*vt, 10, 32)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"*string", "int32", *vt}
			}
			return 0, err
		}
		r, err := ToInt32(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "*string"
		}
		return r, err

	}
	return 0, ErrNoNumConvert
}

func ToInt32P(v interface{}) (*int32, error) {
	if v == nil {
		return nil, nil
	}
	switch vt := v.(type) {

	case int8:
		casted := int32(vt)
		return &casted, nil
	case *int8:
		if vt == nil {
			return nil, nil
		}
		casted := int32(*vt)
		return &casted, nil

	case int16:
		casted := int32(vt)
		return &casted, nil
	case *int16:
		if vt == nil {
			return nil, nil
		}
		casted := int32(*vt)
		return &casted, nil

	case int32:
		return &vt, nil
	case *int32:
		return vt, nil

	case int64:
		if vt < int64(minInt32) || int64(maxInt32) < vt {
			return nil, &RangeError{"int64", "*int32", vt}
		}
		casted := int32(vt)
		return &casted, nil
	case *int64:
		if vt == nil {
			return nil, nil
		}
		if *vt < int64(minInt32) || int64(maxInt32) < *vt {
			return nil, &RangeError{"*int64", "*int32", *vt}
		}
		casted := int32(*vt)
		return &casted, nil

	case int:
		if vt < int(minInt32) || int(maxInt32) < vt {
			return nil, &RangeError{"int", "*int32", vt}
		}
		casted := int32(vt)
		return &casted, nil
	case *int:
		if vt == nil {
			return nil, nil
		}
		if *vt < int(minInt32) || int(maxInt32) < *vt {
			return nil, &RangeError{"*int", "*int32", *vt}
		}
		casted := int32(*vt)
		return &casted, nil

	case uint8:
		casted := int32(vt)
		return &casted, nil
	case *uint8:
		if vt == nil {
			return nil, nil
		}
		casted := int32(*vt)
		return &casted, nil

	case uint16:
		casted := int32(vt)
		return &casted, nil
	case *uint16:
		if vt == nil {
			return nil, nil
		}
		casted := int32(*vt)
		return &casted, nil

	case uint32:
		if uint32(maxInt32) < vt {
			return nil, &RangeError{"uint32", "*int32", vt}
		}
		casted := int32(vt)
		return &casted, nil
	case *uint32:
		if vt == nil {
			return nil, nil
		}
		if uint32(maxInt32) < *vt {
			return nil, &RangeError{"*uint32", "*int32", *vt}
		}
		casted := int32(*vt)
		return &casted, nil

	case uint64:
		if uint64(maxInt32) < vt {
			return nil, &RangeError{"uint64", "*int32", vt}
		}
		casted := int32(vt)
		return &casted, nil
	case *uint64:
		if vt == nil {
			return nil, nil
		}
		if uint64(maxInt32) < *vt {
			return nil, &RangeError{"*uint64", "*int32", *vt}
		}
		casted := int32(*vt)
		return &casted, nil

	case uint:
		if uint(maxInt32) < vt {
			return nil, &RangeError{"uint", "*int32", vt}
		}
		casted := int32(vt)
		return &casted, nil
	case *uint:
		if vt == nil {
			return nil, nil
		}
		if uint(maxInt32) < *vt {
			return nil, &RangeError{"*uint", "*int32", *vt}
		}
		casted := int32(*vt)
		return &casted, nil

	case string:
		n, err := strconv.ParseInt(vt, 10, 32)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"string", "*int32", vt}
			}
			return nil, err
		}
		r, err := ToInt32P(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "string"
		}
		return r, err
	case *string:
		if vt == nil {
			return nil, nil
		}
		n, err := strconv.ParseInt(*vt, 10, 32)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"*string", "*int32", *vt}
			}
			return nil, err
		}
		r, err := ToInt32P(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "*string"
		}
		return r, err

	}
	return nil, ErrNoNumConvert
}
