// Code generated by "gen-int -t int64 -o convert/int64.go"; DO NOT EDIT.
package convert

import (
	"errors"
	"strconv"
)

func ToInt64(v interface{}) (int64, error) {
	if v == nil {
		return 0, ErrNil
	}
	switch vt := v.(type) {

	case int8:
		return int64(vt), nil
	case *int8:
		if vt == nil {
			return 0, ErrNil
		}
		return int64(*vt), nil

	case int16:
		return int64(vt), nil
	case *int16:
		if vt == nil {
			return 0, ErrNil
		}
		return int64(*vt), nil

	case int32:
		return int64(vt), nil
	case *int32:
		if vt == nil {
			return 0, ErrNil
		}
		return int64(*vt), nil

	case int64:
		return vt, nil
	case *int64:
		if vt == nil {
			return 0, ErrNil
		}
		return *vt, nil

	case int:
		if vt < int(minInt64) || int(maxInt64) < vt {
			return 0, &RangeError{"int", "int64", vt}
		}
		return int64(vt), nil
	case *int:
		if vt == nil {
			return 0, ErrNil
		}
		if *vt < int(minInt64) || int(maxInt64) < *vt {
			return 0, &RangeError{"*int", "int64", *vt}
		}
		return int64(*vt), nil

	case uint8:
		return int64(vt), nil
	case *uint8:
		if vt == nil {
			return 0, ErrNil
		}
		return int64(*vt), nil

	case uint16:
		return int64(vt), nil
	case *uint16:
		if vt == nil {
			return 0, ErrNil
		}
		return int64(*vt), nil

	case uint32:
		return int64(vt), nil
	case *uint32:
		if vt == nil {
			return 0, ErrNil
		}
		return int64(*vt), nil

	case uint64:
		if uint64(maxInt64) < vt {
			return 0, &RangeError{"uint64", "int64", vt}
		}
		return int64(vt), nil
	case *uint64:
		if vt == nil {
			return 0, ErrNil
		}
		if uint64(maxInt64) < *vt {
			return 0, &RangeError{"*uint64", "int64", *vt}
		}
		return int64(*vt), nil

	case uint:
		if uint(maxInt64) < vt {
			return 0, &RangeError{"uint", "int64", vt}
		}
		return int64(vt), nil
	case *uint:
		if vt == nil {
			return 0, ErrNil
		}
		if uint(maxInt64) < *vt {
			return 0, &RangeError{"*uint", "int64", *vt}
		}
		return int64(*vt), nil

	case string:
		n, err := strconv.ParseInt(vt, 10, 64)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"string", "int64", vt}
			}
			return 0, err
		}
		r, err := ToInt64(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "string"
		}
		return r, err
	case *string:
		if vt == nil {
			return 0, ErrNil
		}
		n, err := strconv.ParseInt(*vt, 10, 64)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"*string", "int64", *vt}
			}
			return 0, err
		}
		r, err := ToInt64(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "*string"
		}
		return r, err

	}
	return 0, ErrNoNumConvert
}

func ToInt64P(v interface{}) (*int64, error) {
	if v == nil {
		return nil, nil
	}
	switch vt := v.(type) {

	case int8:
		casted := int64(vt)
		return &casted, nil
	case *int8:
		if vt == nil {
			return nil, nil
		}
		casted := int64(*vt)
		return &casted, nil

	case int16:
		casted := int64(vt)
		return &casted, nil
	case *int16:
		if vt == nil {
			return nil, nil
		}
		casted := int64(*vt)
		return &casted, nil

	case int32:
		casted := int64(vt)
		return &casted, nil
	case *int32:
		if vt == nil {
			return nil, nil
		}
		casted := int64(*vt)
		return &casted, nil

	case int64:
		return &vt, nil
	case *int64:
		return vt, nil

	case int:
		if vt < int(minInt64) || int(maxInt64) < vt {
			return nil, &RangeError{"int", "*int64", vt}
		}
		casted := int64(vt)
		return &casted, nil
	case *int:
		if vt == nil {
			return nil, nil
		}
		if *vt < int(minInt64) || int(maxInt64) < *vt {
			return nil, &RangeError{"*int", "*int64", *vt}
		}
		casted := int64(*vt)
		return &casted, nil

	case uint8:
		casted := int64(vt)
		return &casted, nil
	case *uint8:
		if vt == nil {
			return nil, nil
		}
		casted := int64(*vt)
		return &casted, nil

	case uint16:
		casted := int64(vt)
		return &casted, nil
	case *uint16:
		if vt == nil {
			return nil, nil
		}
		casted := int64(*vt)
		return &casted, nil

	case uint32:
		casted := int64(vt)
		return &casted, nil
	case *uint32:
		if vt == nil {
			return nil, nil
		}
		casted := int64(*vt)
		return &casted, nil

	case uint64:
		if uint64(maxInt64) < vt {
			return nil, &RangeError{"uint64", "*int64", vt}
		}
		casted := int64(vt)
		return &casted, nil
	case *uint64:
		if vt == nil {
			return nil, nil
		}
		if uint64(maxInt64) < *vt {
			return nil, &RangeError{"*uint64", "*int64", *vt}
		}
		casted := int64(*vt)
		return &casted, nil

	case uint:
		if uint(maxInt64) < vt {
			return nil, &RangeError{"uint", "*int64", vt}
		}
		casted := int64(vt)
		return &casted, nil
	case *uint:
		if vt == nil {
			return nil, nil
		}
		if uint(maxInt64) < *vt {
			return nil, &RangeError{"*uint", "*int64", *vt}
		}
		casted := int64(*vt)
		return &casted, nil

	case string:
		n, err := strconv.ParseInt(vt, 10, 64)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"string", "*int64", vt}
			}
			return nil, err
		}
		r, err := ToInt64P(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "string"
		}
		return r, err
	case *string:
		if vt == nil {
			return nil, nil
		}
		n, err := strconv.ParseInt(*vt, 10, 64)
		if err != nil {
			if errors.Is(err, strconv.ErrRange) {
				err = &RangeError{"*string", "*int64", *vt}
			}
			return nil, err
		}
		r, err := ToInt64P(n)
		if err, ok := err.(*RangeError); ok && err != nil {
			err.from = "*string"
		}
		return r, err

	}
	return nil, ErrNoNumConvert
}
